version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\axsh\openvdc
clone_depth: 10

environment:
  GOPATH: C:\gopath

cache:
  - '%GOPATH%\.cache -> vendor\vendor.json'

platform:
  - x64

install:
  # some helpful output for debugging builds
  - go version
  - go env

build_script:
  - set PATH=C:\gopath\bin;%PATH%
  - go run ./internal/build/main.go

deploy: off
