hypervisor-name = "lxc"
zk-addr = "127.0.0.1:2181"
script-path="/etc/openvdc/scripts/"

[bridges]
	[bridges.linux]
	name = "br0"
	up-script = "linux-bridge-up.sh"
	down-script = "linux-bridge-down.sh"

	[bridges.ovs]
	name = "ovs-vsctl"
	up-script = "ovs-up.sh"
	down-script = "ovs-down.sh"
