[zookeeper]
# endpoint = "zk://localhost/openvdc"

[executor-api]
# listen = "0.0.0.0:19372"
# advertise-ip = "192.168.56.150"

[console]

[console.ssh]
# listen = ""
# advertise-ip = "192.168.56.150"
