[hypervisor]
# driver = null
script-path="/etc/openvdc/scripts/"

[zookeeper]
# endpoint = "zk://localhost/openvdc"

[bridges]
	[bridges.linux]
	name = "br0"
	up-script = "linux-bridge-up.sh"
	down-script = "linux-bridge-down.sh"

	[bridges.ovs]
	name = "br0"
	up-script = "ovs-up.sh"
	down-script = "ovs-down.sh"
